[update] Arnaud joined Doctolib
lescastcodeurs/lescastcodeurs.com pull request #107
Opened 2022-10-20 21:52 UTC by aheritier

2022-10-21 11:58 UTC, marcwrobel requested changes

2022-10-21 11:58 UTC, marcwrobel commented on _team/ArnaudHeritier.md
>  Arnaud est diplômé d'un [DESS en génie des logiciels applicatifs](http://ta-stl.infop6.jussieu.fr/) (renommé DESS Technologies Applicatives depuis) à l'université de Jussieu, Paris VI.
C'est un peu en dehors de cette PR mais le lien http://ta-stl.infop6.jussieu.fr/ n'a plus l'air de fonctionner très bien.

2022-10-22 09:18 UTC, aheritier commented on _team/ArnaudHeritier.md
>  Arnaud est diplômé d'un [DESS en génie des logiciels applicatifs](http://ta-stl.infop6.jussieu.fr/) (renommé DESS Technologies Applicatives depuis) à l'université de Jussieu, Paris VI.
ils ont tué mon DESS :(

2022-10-22 09:36 UTC, aheritier commented
fixed @marcwrobel

2022-10-22 10:54 UTC, marcwrobel commented on _team/ArnaudHeritier.md
>  Arnaud est diplômé d'un [DESS en génie des logiciels applicatifs](http://ta-stl.infop6.jussieu.fr/) (renommé DESS Technologies Applicatives depuis) à l'université de Jussieu, Paris VI.
Oh !

2022-10-22 10:54 UTC, marcwrobel approved these changes

2022-10-22 10:55 UTC, merged

2022-10-22 10:55 UTC, marcwrobel commented
Et félicitation pour ton nouveau poste @aheritier  ! ;)

2022-10-22 11:19 UTC, aheritier commented
Merci